import { notFound } from "next/navigation";
import Link from "next/link";
import { Container } from "@/components/shell/container";
import { ResearchQuestionCard } from "@/components/project/research-question-card";
import { ProjectMeta } from "@/components/project/project-meta";
import { Button } from "@/components/ui/button";
import { getProjectDetail } from "@/lib/db/queries/projects";

export const dynamic = "force-dynamic";

export default async function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const project = await getProjectDetail(id);
  if (!project) notFound();

  return (
    <main className="py-16">
      <Container width="narrow">
        <p className="text-text-dim font-mono text-xs tracking-widest uppercase">
          {project.companyName}
        </p>
        <h1 className="font-display mt-3 text-5xl leading-tight">{project.title}</h1>
        <p className="text-text mt-6 text-lg">{project.endGoal}</p>

        <div className="mt-10">
          <ProjectMeta
            status={project.status}
            applicantCount={project.applicantCount}
            createdAt={project.createdAt}
          />
        </div>

        <section className="mt-16">
          <h2 className="font-display text-3xl">Research questions</h2>
          <p className="text-text-dim mt-2 max-w-prose text-sm">
            Generated by Praxis from the company's brief, edited by {project.companyName}.
          </p>
          <div className="mt-8 space-y-6">
            {project.questions.map((q, i) => (
              <ResearchQuestionCard
                key={q.id}
                question={q.question}
                rationale={q.rationale}
                index={i}
              />
            ))}
          </div>
        </section>

        {project.status === "open" && (
          <section className="border-ink-3 bg-ink-2 mt-16 rounded-md border p-8">
            <h3 className="font-display text-xl">Apply with your team</h3>
            <p className="text-text-dim mt-2 text-sm">
              Sign in as a researcher, form a team, and submit a pitch. Match score is computed from
              your team's publication concepts.
            </p>
            <Button asChild className="mt-6">
              <Link href={`/projects/${project.id}/apply`}>Apply with my team →</Link>
            </Button>
          </section>
        )}
      </Container>
    </main>
  );
}
